name: DropTube CI

on:
    push:
        branches: [master, stable]
        paths:
            - "src/**"
            - "Cargo.toml"
            - "Cargo.lock"
    pull_request:
        branches: [master, stable]
        paths:
            - "src/**"
            - "Cargo.toml"
            - "Cargo.lock"
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and Test
        steps:
            - uses: actions/checkout@v7
            - name: Build
              run: cargo build --verbose

            - uses: taiki-e/install-action@nextest
            - name: Run Tests
              run: cargo nextest run
